// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.8.166
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FileComparer
{
    static class Vsix
    {
        public const string Id = "5f64001b-614e-424d-b84a-f462ce628238";
        public const string Name = "File Comparer";
        public const string Description = "Extension to compare two files in Solution Explorer.";
        public const string Language = "en-US";
        public const string Version = "1.0.1";
        public const string Author = "Akhil Mittal";
        public const string Tags = "compare, difference, files, diff, map";
    }
}
