// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.8.166
// </auto-generated>
// ------------------------------------------------------------------------------
namespace FileComparer
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidCompFilesCommandPackageString = "19c1a8db-e8ea-4ae9-aa7c-bd7fa0e03d00";
        public const string guidCompFilesCommandPackageCmdSetString = "9e26acae-cf21-4e04-9007-e9a583df4af8";
        public const string guidImagesString = "fdf71639-4749-4357-8fe7-9881b6f9542d";
        public static Guid guidCompFilesCommandPackage = new Guid(guidCompFilesCommandPackageString);
        public static Guid guidCompFilesCommandPackageCmdSet = new Guid(guidCompFilesCommandPackageCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int CompFilesCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
    }
}
